Given a bank customer, build a neural network-based classifier that can determine whether
they will leave or not in the next 6 months.
Dataset Description: The case study is from an open-source dataset from Kaggle.
The dataset contains 10,000 sample points with 14 distinct features such as
CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance, etc.
Link to the Kaggle project:
https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling
Perform following steps:
1. Read the dataset.
2. Distinguish the feature and target set and divide the data set into training and test sets.
3. Normalize the train and test data.
4. Initialize and build the model. Identify the points of improvement and implement the same.
5. Print the accuracy score and confusion matrix (5 points).

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.shape

(10000, 14)

In [5]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [7]:
df = df.drop(['RowNumber','Surname','CustomerId'], axis = 1)

In [8]:
states = pd.get_dummies(df['Geography'],drop_first = True)
gender = pd.get_dummies(df['Gender'],drop_first = True)
df = df.drop(['Geography','Gender'], axis = 1)
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# df['Geography'] = le.fit_transform(df['Geography'])
# df['Gender'] = le.fit_transform(df['Gender'])

In [9]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1
3,699,39,1,0.00,2,0,0,93826.63,0
4,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0
9996,516,35,10,57369.61,1,1,1,101699.77,0
9997,709,36,7,0.00,1,0,1,42085.58,1
9998,772,42,3,75075.31,2,1,0,92888.52,1
9999,792,28,4,130142.79,1,1,0,38190.78,0

In [10]:
df = pd.concat([df,gender,states], axis = 1)
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Male,Germany,Spain
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,1,0
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [11]:
x = df.drop('Exited', axis = 1)
y = df['Exited']

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30)

In [13]:
x_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Male,Germany,Spain
4230,670,41,10,0.00,3,1,0,81602.02,0,0,0
5694,660,31,6,172325.67,1,0,1,45438.38,0,0,0
3578,704,39,1,124640.51,1,1,0,116511.12,0,1,0
6125,501,34,7,93244.42,1,0,1,199805.63,0,1,0
2719,569,42,9,146100.75,1,1,0,32574.01,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
4720,619,33,3,100488.92,2,0,1,36446.74,0,1,0
726,580,37,9,0.00,2,0,1,77108.66,1,0,0
9075,576,40,9,0.00,2,1,0,112465.19,1,0,0
6941,501,25,6,104013.79,1,1,0,114774.35,1,1,0
1532,661,32,1,145980.23,1,0,1,56636.28,0,1,0

In [14]:
y_train

4230    0
5694    0
3578    1
6125    0
2719    1
       ..
4720    0
726     0
9075    1
6941    0
1532    0
Name: Exited, Length: 7000, dtype: int64

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense #To create hidden layers

model = Sequential()

model.add(Dense(activation = "relu", input_dim = 11,units = 6, kernel_initializer = "uniform"))
model.add(Dense(activation = "relu", units = 6, kernel_initializer = "uniform"))   #Adding second hidden layers
model.add(Dense(activation = "sigmoid", units = 1,kernel_initializer = "uniform"))  #Final neuron will be having siigmoid function

model.compile(optimizer="adam", loss = 'binary_crossentropy', metrics = ['accuracy']) #To compile the Artificial Neural Network. Ussed Binary crossentropy as we just have only two output
model.summary() #3 layers created. 6 neurons in 1st,6neurons in 2nd layer and 1 neuron in last

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 72

 dense_1 (Dense)             (None, 6)                 42

 dense_2 (Dense)             (None, 1)                 7

=================================================================
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
model.fit(x_train,y_train,batch_size=11,epochs=50) #Fitting the ANN to training dataset

Epoch 1/50
637/637 [==============================] - 2s 2ms/step - loss: 0.4972 - accuracy: 0.7943
Epoch 2/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4308 - accuracy: 0.7946
Epoch 3/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4245 - accuracy: 0.7946
Epoch 4/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4193 - accuracy: 0.8139
Epoch 5/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4166 - accuracy: 0.8256
Epoch 6/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4146 - accuracy: 0.8300
Epoch 7/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4130 - accuracy: 0.8290
Epoch 8/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4117 - accuracy: 0.8320
Epoch 9/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4099 - accuracy: 0.8327
Epoch 10/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4095 - accuracy: 0.8337
Epoch 11/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4083 - accuracy: 0.8357
Epoch 12/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4075 - accuracy: 0.8359
Epoch 13/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4071 - accuracy: 0.8349
Epoch 14/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4060 - accuracy: 0.8367
Epoch 15/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4060 - accuracy: 0.8346
Epoch 16/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4054 - accuracy: 0.8363
Epoch 17/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4046 - accuracy: 0.8359
Epoch 18/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4044 - accuracy: 0.8354
Epoch 19/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4035 - accuracy: 0.8353
Epoch 20/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4040 - accuracy: 0.8353
Epoch 21/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4033 - accuracy: 0.8359
Epoch 22/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4032 - accuracy: 0.8359
Epoch 23/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4024 - accuracy: 0.8354
Epoch 24/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4023 - accuracy: 0.8350
Epoch 25/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8356
Epoch 26/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4024 - accuracy: 0.8341
Epoch 27/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8341
Epoch 28/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8353
Epoch 29/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4014 - accuracy: 0.8349
Epoch 30/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8357
Epoch 31/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4014 - accuracy: 0.8373
Epoch 32/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4013 - accuracy: 0.8360
Epoch 33/50
637/637 [==============================] - 2s 3ms/step - loss: 0.4009 - accuracy: 0.8363
Epoch 34/50
637/637 [==============================] - 1s 2ms/step - loss: 0.4005 - accuracy: 0.8356
Epoch 35/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3999 - accuracy: 0.8351
Epoch 36/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3993 - accuracy: 0.8364
Epoch 37/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3991 - accuracy: 0.8370
Epoch 38/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3987 - accuracy: 0.8371
Epoch 39/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3976 - accuracy: 0.8364
Epoch 40/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3980 - accuracy: 0.8357
Epoch 41/50
637/637 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8376
Epoch 42/50
637/637 [==============================] - 2s 3ms/step - loss: 0.3971 - accuracy: 0.8363
Epoch 43/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3962 - accuracy: 0.8380
Epoch 44/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3965 - accuracy: 0.8381
Epoch 45/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3951 - accuracy: 0.8360
Epoch 46/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3953 - accuracy: 0.8356
Epoch 47/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3953 - accuracy: 0.8390
Epoch 48/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3946 - accuracy: 0.8379
Epoch 49/50
637/637 [==============================] - 1s 2ms/step - loss: 0.3950 - accuracy: 0.8387
Epoch 50/50
637/637 [==============================] - 2s 3ms/step - loss: 0.3948 - accuracy: 0.8364

In [18]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)

94/94 [==============================] - 0s 2ms/step

In [19]:
from sklearn import metrics

In [20]:
metrics.accuracy_score(y_test, y_pred)

0.8376666666666667

In [21]:
metrics.confusion_matrix(y_test, y_pred)

array([[2328,   73],
       [ 414,  185]])